#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "$(realpath "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${SCRIPT_DIR}/../bin:/usr/lib"

scryer-prolog -g main -g halt "${SCRIPT_DIR}/scryer/init.pl" "${SCRIPT_DIR}/plwm.pl"  -- "$@"
