name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run:
          DOCKER_BUILDKIT=1 docker build -t plwm:latest .

      - name: Run tests
        run:
          docker run plwm:latest
